### ISSUE TITLE
EndeavourOS icon name is incorrect

### ISSUE THREAD

**Issue by pedrohqb** [bobafetthotmail/refind-theme-regular#47]
EndeavourOS icon is not working as it was renamed from os-endeavouros.png to endeavour.png.

**Comment by bobafetthotmail** [comment]
sorry, I didn't change the name of the source file (the svg file that is used to generate the png files https://github.com/bobafetthotmail/refind-theme-regular/commit/768d9e3b0ec993f0190754ea95f461b33ab11f13

so when I ran some cleanups the new images were re-created with the wrong name.

Fixed with https://github.com/bobafetthotmail/refind-theme-regular/commit/3969875e2f8286ed7b656dbb1ba6cfe2e82fc652
